package com.ruoyi.system.domain;

import com.ruoyi.common.annotation.Excel;
import com.ruoyi.common.core.domain.BaseEntity;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

import java.math.BigDecimal;
import java.util.Date;

/**
 * 学习计划对象 study_plan
 * 
 * @author ruoyi
 * @date 2024-12-18
 */
public class StudyPlan extends BaseEntity
{
    private static final long serialVersionUID = 1L;

    /** 学习计划ID */
    private Long planId;

    /** 用户ID */
    @Excel(name = "用户ID")
    private Long userId;

    /** 学习计划名称 */
    @Excel(name = "学习计划名称")
    private String planName;

    /** 截止日期 */
    @Excel(name = "截止日期", width = 30, dateFormat = "yyyy-MM-dd")
    private Date deadline;

    /** 重要程度(1-5级，5最重要) */
    @Excel(name = "重要程度")
    private Integer priority;

    /** 标签分类(逗号分隔) */
    @Excel(name = "标签分类")
    private String tags;

    /** 是否系统生成每日计划(0否1是) */
    @Excel(name = "是否系统生成每日计划")
    private Integer autoGenerateDaily;

    /** 自定义每日计划内容 */
    @Excel(name = "自定义每日计划内容")
    private String dailyPlan;

    /** 是否完成(0未完成1已完成) */
    @Excel(name = "是否完成")
    private Integer isCompleted;

    /** 完成时间 */
    @Excel(name = "完成时间", width = 30, dateFormat = "yyyy-MM-dd HH:mm:ss")
    private Date completedTime;

    /** 预计学习时长(小时) */
    @Excel(name = "预计学习时长")
    private BigDecimal estimatedHours;

    /** 实际学习时长(小时) */
    @Excel(name = "实际学习时长")
    private BigDecimal actualHours;

    /** 学科/类别 */
    @Excel(name = "学科")
    private String subject;

    /** 计划描述 */
    @Excel(name = "计划描述")
    private String description;

    public void setPlanId(Long planId) 
    {
        this.planId = planId;
    }

    public Long getPlanId() 
    {
        return planId;
    }
    public void setUserId(Long userId) 
    {
        this.userId = userId;
    }

    public Long getUserId() 
    {
        return userId;
    }
    public void setPlanName(String planName) 
    {
        this.planName = planName;
    }

    public String getPlanName() 
    {
        return planName;
    }
    public void setDeadline(Date deadline) 
    {
        this.deadline = deadline;
    }

    public Date getDeadline() 
    {
        return deadline;
    }
    public void setPriority(Integer priority) 
    {
        this.priority = priority;
    }

    public Integer getPriority() 
    {
        return priority;
    }
    public void setTags(String tags) 
    {
        this.tags = tags;
    }

    public String getTags() 
    {
        return tags;
    }
    public void setAutoGenerateDaily(Integer autoGenerateDaily) 
    {
        this.autoGenerateDaily = autoGenerateDaily;
    }

    public Integer getAutoGenerateDaily() 
    {
        return autoGenerateDaily;
    }
    public void setDailyPlan(String dailyPlan) 
    {
        this.dailyPlan = dailyPlan;
    }

    public String getDailyPlan() 
    {
        return dailyPlan;
    }
    public void setIsCompleted(Integer isCompleted) 
    {
        this.isCompleted = isCompleted;
    }

    public Integer getIsCompleted() 
    {
        return isCompleted;
    }
    public void setCompletedTime(Date completedTime) 
    {
        this.completedTime = completedTime;
    }

    public Date getCompletedTime() 
    {
        return completedTime;
    }
    public void setEstimatedHours(BigDecimal estimatedHours) 
    {
        this.estimatedHours = estimatedHours;
    }

    public BigDecimal getEstimatedHours() 
    {
        return estimatedHours;
    }
    public void setActualHours(BigDecimal actualHours) 
    {
        this.actualHours = actualHours;
    }

    public BigDecimal getActualHours() 
    {
        return actualHours;
    }
    public void setSubject(String subject) 
    {
        this.subject = subject;
    }

    public String getSubject() 
    {
        return subject;
    }
    public void setDescription(String description) 
    {
        this.description = description;
    }

    public String getDescription() 
    {
        return description;
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this,ToStringStyle.MULTI_LINE_STYLE)
            .append("planId", getPlanId())
            .append("userId", getUserId())
            .append("planName", getPlanName())
            .append("deadline", getDeadline())
            .append("priority", getPriority())
            .append("tags", getTags())
            .append("autoGenerateDaily", getAutoGenerateDaily())
            .append("dailyPlan", getDailyPlan())
            .append("isCompleted", getIsCompleted())
            .append("completedTime", getCompletedTime())
            .append("estimatedHours", getEstimatedHours())
            .append("actualHours", getActualHours())
            .append("subject", getSubject())
            .append("description", getDescription())
            .append("createTime", getCreateTime())
            .append("updateTime", getUpdateTime())
            .toString();
    }
}